/*
 * This file was generated by the Gradle 'init' task.
 *
 * Copyright (c) 2025.  Jefferson Lab (JLab). All rights reserved. Permission
 * to use, copy, modify, and distribute  this software and its documentation for
 * educational, research, and not-for-profit purposes, without fee and without a
 * signed licensing agreement.
 *
 * IN NO EVENT SHALL JLAB BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL
 * INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING
 * OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF JLAB HAS
 * BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * JLAB SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE. THE CLARA SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY,
 * PROVIDED HEREUNDER IS PROVIDED "AS IS". JLAB HAS NO OBLIGATION TO PROVIDE
 * MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 * This software was developed under the United States Government license.
 * For more information contact maintainer at jzarling@jlab.org
 * Department of Experimental Nuclear Physics, Jefferson Lab.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
}

group = "org.jlab.coda"
version = "3.3" // emu.version

java {
    toolchain { languageVersion.set(JavaLanguageVersion.of(15)) }
    withJavadocJar()
}

repositories {
    mavenLocal()
    mavenCentral()
    // Local flat dir (keeps Ant behavior of using jars in java/jars)
    // You can also just rely on the files() below without flatDir, but this
    // enables notations like "name: 'disruptor-3.4.3'" if desired.
    flatDir { dirs("java/jars") }
}

val srcDir = layout.projectDirectory.dir("java")
val docDir = layout.projectDirectory.dir("doc/javadoc")
val scriptsDir = layout.projectDirectory.dir("scripts")
val buildLib = layout.buildDirectory.dir("lib")

// Optional env
val coda: String? = System.getenv("CODA")
val prefix: String? = (findProperty("prefix") as String?) // pass with -Pprefix=/path

// Source layout to match Ant (sources in ./java)
sourceSets {
    main {
        java.setSrcDirs(listOf("java"))
        resources {
            // Keep Ant-style resources under java/**
            setSrcDirs(listOf("java"))
            include("**/*.properties", "**/*.png", "**/*.jpg", "**/*.gif", "**/*.xml")
            // exclude .java so it isn't duplicated as a resource
            exclude("**/*.java")
        }
    }
    test {
        // default layout; adjust if you have tests under java/
    }
}

// Dependencies: keep local jars and (optionally) CODA/common/jar on classpath
dependencies {
    // Everything in java/jars/*.jar (like disruptor-3.4.3.jar, swing-layout.jar)
    implementation(files("java/jars").asFileTree.matching { include("*.jar") })

    // If CODA is defined, add $CODA/common/jar/*.jar (keeps Ant CODA_cp logic)
    if (coda != null) {
        implementation(fileTree("$coda/common/jar") { include("*.jar") })
    }

    // Add your test deps if needed:
    testImplementation(platform("org.junit:junit-bom:5.10.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test {
    useJUnitPlatform()
}

// Jar name "emu-<version>.jar" like Ant
tasks.jar {
    archiveBaseName.set("emu")
    archiveVersion.set(project.version.toString())
    destinationDirectory.set(buildLib)

    // Use the Ant manifest file
    val antManifest = srcDir.file("org/jlab/coda/emu/manifest.mf").asFile
    if (antManifest.exists()) {
        manifest {
            from(antManifest)
        }
    }
}

tasks.register("env") {
    // Provide only primitives/strings as inputs
    inputs.property("srcDir", layout.projectDirectory.dir("java").asFile.absolutePath)
    inputs.property("buildDir", layout.buildDirectory.asFile.get().absolutePath)
    inputs.property("buildLib", layout.buildDirectory.dir("lib").get().asFile.absolutePath)
    inputs.property("docDir", layout.projectDirectory.dir("doc/javadoc").asFile.absolutePath)
    inputs.property("CODA", System.getenv("CODA") ?: "(unset)")
    inputs.property("prefix", (findProperty("prefix") as String?) ?: "(unset)")

    doLast {
        val p = inputs.properties
        println("Gradle environment:")
        println("  src.dir       = ${p["srcDir"]}")
        println("  build.dir     = ${p["buildDir"]}")
        println("  build.lib     = ${p["buildLib"]}")
        println("  doc.dir       = ${p["docDir"]}")
        println("  CODA          = ${p["CODA"]}")
        println("  prefix        = ${p["prefix"]}")
    }
}
// Ant clean/cleanall equivalents (Gradle already has clean)
tasks.register("cleanall") {
    group = "build"
    description = "Remove all generated files (build + javadoc)."
    dependsOn("clean")
    doLast {
        delete(docDir)
    }
}

// Javadoc (public) — Ant "javadoc"
tasks.javadoc {
    destinationDir = docDir.asFile
    (options as StandardJavadocDocletOptions).apply {
        memberLevel = JavadocMemberLevel.PUBLIC
        addBooleanOption("use", true)
        // Keep package filter similar to Ant's packagenames if desired:
        // packages("org.jlab.coda.emu") // or leave default to include all
        // sourcepath is derived from sourceSets; no need to set explicitly
    }
}

// Javadoc (developer, package access) — Ant "developdoc"
tasks.register<Javadoc>("developdoc") {
    group = "documentation"
    description = "Create javadoc for developer (package access)."
    source = sourceSets.main.get().allJava
    classpath = sourceSets.main.get().compileClasspath
    destinationDir = docDir.asFile
    (options as StandardJavadocDocletOptions).apply {
        memberLevel = JavadocMemberLevel.PACKAGE
        addBooleanOption("use", true)
    }
}

// Ant "undoc"
tasks.register("undoc") {
    group = "documentation"
    description = "Remove all javadoc."
    doLast { delete(docDir) }
}

// ---------- Install / Uninstall (keeps Ant semantics) ----------

val jarName = provider { tasks.jar.get().archiveFileName.get() }
val allJarNames = "emu-*.jar"
val allDisNames = "disruptor-*.jar"
val disJarName = "disruptor-3.4.3.jar"
val slJarName = "swing-layout.jar"

fun File.copyExecutableBitsIfScript() {
    // Gradle's Copy can set fileMode, but if you want per-file preservation,
    // you could tweak here. For simplicity we'll set 0755 for all copied scripts.
}

// Helpers
fun requireInstallDir() {
    if (prefix == null && coda == null) {
        throw GradleException("CODA env var not defined and -Pprefix not used, jar NOT installed")
    }
}

// Prepare dirs (Gradle will create as needed on copy; we mirror Ant flow)
tasks.register("prepare") {
    // No-op; Gradle tasks create dirs on demand. Kept to mirror Ant target graph.
}

// Copy scripts to <prefix>/bin or $CODA/common/bin
val installScriptsInPrefix = tasks.register<Copy>("installScriptsInPrefix") {
    onlyIf { prefix != null }
    from(scriptsDir)
    into(file("$prefix/bin"))
    include("*")
    // Clean existing matching scripts first like Ant
    doFirst { delete(fileTree("$prefix/bin") { include("coda_emu*") }) }
    // Make scripts executable
    filePermissions {
        // rwxr-xr-x (0755)
        user { read = true; write = true; execute = true }
        group { read = true; execute = true }
        other { read = true; execute = true }
    }
}

val installScriptsInCODA = tasks.register<Copy>("installScriptsInCODA") {
    onlyIf { prefix == null && coda != null }
    from(scriptsDir)
    into(file("$coda/common/bin"))
    include("*")
    doFirst { delete(fileTree("$coda/common/bin") { include("coda_emu*") }) }
    filePermissions {
        // rwxr-xr-x (0755)
        user { read = true; write = true; execute = true }
        group { read = true; execute = true }
        other { read = true; execute = true }
    }
}

// Install jar + local deps to <prefix>/jar or $CODA/common/jar
val installInPrefix = tasks.register("installInPrefix") {
    onlyIf { prefix != null }
    dependsOn(tasks.jar)
    doLast {
        val dest = file("$prefix/jar")
        dest.mkdirs()
        // Remove old emu/disruptor jars like Ant
        delete(fileTree(dest) { include(allJarNames) })
        delete(fileTree(dest) { include(allDisNames) })
        // Copy the new jar and the two dependency jars (from java/jars)
        copy {
            from(tasks.jar.get().archiveFile)
            into(dest)
        }
        copy {
            from("java/jars/$disJarName")
            into(dest)
        }
        copy {
            from("java/jars/$slJarName")
            into(dest)
        }
        println("Installed $jarName, $disJarName, $slJarName into $dest")
    }
}

val installInCODA = tasks.register("installInCODA") {
    onlyIf { prefix == null && coda != null }
    dependsOn(tasks.jar)
    doLast {
        val dest = file("$coda/common/jar")
        dest.mkdirs()
        delete(fileTree(dest) { include(allJarNames) })
        delete(fileTree(dest) { include(allDisNames) })
        copy { from(tasks.jar.get().archiveFile); into(dest) }
        copy { from("java/jars/$disJarName"); into(dest) }
        copy { from("java/jars/$slJarName");  into(dest) }
        println("Installed $jarName, $disJarName, $slJarName into $dest")
    }
}

// Unified "install" like Ant (fails if neither prefix nor CODA)
tasks.register("install") {
    group = "distribution"
    description = "Installs jar and scripts to prefix or CODA."
    dependsOn(tasks.jar)
    dependsOn(installInPrefix, installInCODA, installScriptsInPrefix, installScriptsInCODA)
    doFirst { requireInstallDir() }
}

// Uninstall jar(s) from prefix or CODA
val uninstallFromPrefix = tasks.register("uninstallFromPrefix") {
    onlyIf { prefix != null }
    doLast {
        delete(
            file("$prefix/jar/${jarName.get()}"),
            file("$prefix/jar/$disJarName"),
            file("$prefix/jar/$slJarName")
        )
        println("Removed $jarName, $disJarName, $slJarName from $prefix/jar")
    }
}

val uninstallFromCODA = tasks.register("uninstallFromCODA") {
    onlyIf { prefix == null && coda != null }
    doLast {
        delete(
            file("$coda/common/jar/${jarName.get()}"),
            file("$coda/common/jar/$disJarName"),
            file("$coda/common/jar/$slJarName")
        )
        println("Removed $jarName, $disJarName, $slJarName from $coda/common/jar")
    }
}

tasks.register("uninstall") {
    group = "distribution"
    description = "Uninstalls jar from prefix or CODA."
    dependsOn(uninstallFromPrefix, uninstallFromCODA)
    doFirst {
        if (prefix == null && coda == null) {
            throw GradleException("Installation directory not defined, jar NOT installed")
        }
    }
}

// Convenience (Ant "all" == clean, compile, jar)
tasks.register("all") {
    group = "build"
    description = "Clean, compile, and create jar."
    dependsOn("clean", "jar")
}

// Default task like Ant "default=compile" (here: assemble jar)
defaultTasks("jar")
