./emu_test_producer ROC1 EMU1 &
./emu_test_producer ROC2 EMU1 &
./emu_test_producer ROC3 EMU1 &
./emu_test_producer ROC4 EMU1 &
./emu_test_producer ROC5 EMU1 &
./emu_test_producer ROC6 EMU1 &
./emu_test_producer ROC7 EMU1 &
./emu_test_producer ROC8 EMU1 &
./emu_test_producer ROC9 EMU1 &
./emu_test_producer ROC10 EMU1 &
./emu_test_producer ROC11 EMU1 &
./emu_test_producer ROC12 EMU1 &
./emu_test_producer ROC13 EMU1 &
./emu_test_producer ROC14 EMU1 &
./emu_test_producer ROC15 EMU1 &
./emu_test_producer ROC16 EMU1 &
./emu_test_producer ROC17 EMU1 &
./emu_test_producer ROC18 EMU1 &
./emu_test_producer ROC19 EMU1 &
./emu_test_producer ROC20 EMU1 &

