#!/bin/csh -f

# Script to start up a cMsg server monitor
# Optional first argument is the cMsg server host name

if ($#argv > 1) then
    echo
    echo "Usage: cmsg_monitor <hostname(optional)>"
    echo
    exit
else if ($#argv == 1) then
    if ($1 == '-h' || $1 == '-help') then
        echo
        echo "Usage: cmsg_monitor <hostname(optional)>"
        echo
        exit
    endif
endif

set udl="cMsg://localhost:45000/cMsg/${EXPID}?cmsgpassword=${EXPID}"

if ($#argv > 0) then
    set udl="cMsg://${1}:45000/cMsg/${EXPID}?cmsgpassword=${EXPID}"
endif

$JAVA_HOME/bin/java -cp $CODA/common/jar/\* \
    -XX:+PerfDisableSharedMem \
    -Djava.net.preferIPv4Stack=true \
    -Djava.library.path=$CODA/$MACHINE/lib \
    org.jlab.coda.cMsg.apps.cMsgMonitor -n monitor -u "$udl"
