#!/bin/csh -f

# Script to start up a CODA EMU Primary Event Builder
# First argument is the name of the component

if ($#argv < 1) then
  echo "Usage: coda_emu_peb <name> <rc address(optional)>"
  echo "(Note valid addresses: ipv4 dot decimal)"
  exit
endif

#setenv PATH $CODA/$MACHINE/bin
#setenv LD_LIBRARY_PATH $CODA/$MACHINE/lib

#setenv MALLOC_ARENA_MAX 2

if ($#argv > 1) then
$JAVA_HOME/bin/java -cp $CODA/common/jar/\* \
    -XX:+PerfDisableSharedMem \
    -XX:+UseG1GC \
    -DrcAddr=$2 \
    -Djava.net.preferIPv4Stack=true \
    -Djava.library.path=$CODA/$MACHINE/lib \
    -DcmsgUDL="rc://multicast/"$EXPID \
    -Dname=$1 \
    -Dtype=PEB org.jlab.coda.emu.EmuFactory
else
$JAVA_HOME/bin/java -cp $CODA/common/jar/\* \
    -XX:+PerfDisableSharedMem \
    -XX:+UseG1GC \
    -Djava.net.preferIPv4Stack=true \
    -Djava.library.path=$CODA/$MACHINE/lib \
    -DcmsgUDL="rc://multicast/"$EXPID \
    -Dname=$1 \
    -Dtype=PEB org.jlab.coda.emu.EmuFactory
endif