#!/bin/csh -f

# Script to start up a CODA EMU farm control component
# First argument is the name of the component

if ($#argv < 1) then
  echo "Usage: coda_emu_fcs <emu_name>"
  exit
endif

#setenv PATH $CODA/$MACHINE/bin
#setenv LD_LIBRARY_PATH $CODA/$MACHINE/lib

$JAVA_HOME/bin/java -cp $CODA/common/jar/\* \
    -Djava.net.preferIPv4Stack=true \
    -Djava.library.path=$CODA/$MACHINE/lib \
    -DcmsgUDL="rc://multicast/"$EXPID \
    -Dname=$1 \
    -Dtype=FCS org.jlab.coda.emu.EmuFactory
