# Automatic generation of javadoc files for EMU's Java code
# on the emu-3.3 branch which will be copied and checked into the gh-pages branch.
name: Documentation generation CI

on:
  push:
    branches: [ emu-3.3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # checkout the emu-3.3 branch
      - uses: actions/checkout@v2

      # generate the javadoc files
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Javadoc Action
        run: ant -noinput -buildfile build.xml developdoc

      # clean up the javadoc files including removing timestamps. OPTIONAL.
      - name: Tidy up the javadocs
        id: tidy
        uses: cicirello/javadoc-cleanup@v1
        with:
          path-to-root: doc/javadoc

      # store the doc files
      - name: Upload Output Directory
        uses: actions/upload-artifact@v2
        with:
          name: doc-files
          path: doc
          retention-days: 1

  copy:

    runs-on: ubuntu-latest
    needs: build

    steps:
      # checkout the gh-pages branch
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      # download the doc files, most of which are generated above
      - name: Download Output Directory
        uses: actions/download-artifact@v2
        with:
          name: doc-files
          path: doc-3.3

      # add, commit and push to gh-pages
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Carl Timmer
          author_email: timmer@jlab.org
          message: 'Update docs'
          branch: gh-pages
          add: '["doc-3.3/javadoc/", "doc-3.3/usersGuide/emuUsersGuide.pdf"]'
