# This defines flags which can implement (or not) features
# in a way compatible with this OS

include $(BMS_HOME)/Makefile.GNU

OSXFLAGS = -DDarwin

CFLAGS   += $(OSXFLAGS) - O3 -Wall -fPIC
CXXFLAGS += $(OSXFLAGS) -O 3 -Wall -fPIC

# flags to link the .so
LD_SO_FLAGS = -r -dylib 
LD +=  -all_load

#/usr/lib/dylib1.o 

SHLIB_LD  += -dylib

#/usr/lib/dylib1.o 
MISC_LIBS += -ldl
